version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "k1LoW"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "github.com/pb33f/libopenapi"
        versions: ["0.17.x"]
      - dependency-name: "github.com/pb33f/libopenapi-validator"
        versions: ["0.2.x"]
      - dependency-name: "github.com/chromedp/chromedp"
        versions: ["0.11.x"]
      - dependency-name: "github.com/goccy/go-json"
        versions: ["0.10.4"] # ref: https://github.com/goccy/go-json/issues/529
    open-pull-requests-limit: 10
    assignees:
      - "k1LoW"
